### ISSUE TITLE
Wishlist item: Binary Yes/no community map

### ISSUE THREAD

**Issue by yochannah** [open-life-science/ols-stats#8]
Right now all our maps show scales from 0-N, which makes it a little hard to determine which countries OLS has light presence in. 

Example here: https://openlifesci.org/ols-stats/community/explore_location.html 

Could we have a version of the map that has one colour for 0/null (white or gray maybe) and another colour for "any participants at all"? I think this would more clearly show our international diversity. 

@NPDebs this is non-urgent, but might be fun.

**Comment by NPDebs** [comment]
You're right, it'll be fun, as I've never had to touch this before now. Added to the wishlist, next to Full Text Search. :)

**Comment by yochannah** [comment]
fixed by @bebatut
